version: '3'
services:
  tis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    container_name: tis
    image: tis
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - ./src:/var/www/html/
    working_dir: /var/www/html/
