apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: tis
  name: tis
  namespace: jasmine-tis
spec:
  clusterIP:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: tis
  sessionAffinity: None
  type: NodePort